export const categories = [
    { type: 'Apartment', icon: '/icons/icons8-apartment-64.png' },
    { type: 'House', icon: '/icons/icons8-house-64.png' },
    { type: 'Bed & Breakfast', icon: '/icons/icons8-breakfast-64.png' },
    { type: 'Townhouse', icon: '/icons/icons8-townhome-64.png' },
    { type: 'Other', icon: '/icons/icons8-categorize-64.png' },
    { type: 'Loft', icon: '/icons/icons8-loft-64.png' },
    { type: 'Dorm', icon: '/icons/icons8-dormitory-64.png' },
    { type: 'Guesthouse', icon: '/icons/icons8-neighbor-64.png' },
    { type: 'Boat', icon: '/icons/icons8-sailboat-64.png' },
    { type: 'Bungalow', icon: '/icons/icons8-bungalow-64.png' },
    { type: 'Serviced apartment', icon: '/icons/icons8-condo-64.png' },
    { type: 'Condominium', icon: '/icons/icons8-condominium-64.png' },
    { type: 'Boutique hotel', icon: '/icons/icons8-hotel-building-64.png' },
    { type: 'Cabin', icon: '/icons/icons8-cabin-64.png' },
    { type: 'Hostel', icon: '/icons/icons8-hostel-64.png' },
    { type: 'Villa', icon: '/icons/icons8-villa-64.png' },
    { type: 'Camper/RV', icon: '/icons/icons8-camper-64.png' },
    { type: 'Chalet', icon: '/icons/icons8-chalet-64.png' },
    { type: 'Tent', icon: '/icons/icons8-camping-tent-64.png' },
    { type: 'Castle', icon: '/icons/icons8-castle-64.png' },
    { type: 'Yurt', icon: '/icons/icons8-yurt-64.png' },
    { type: 'Hut', icon: '/icons/icons8-hut-64.png' },
    { type: 'Lighthouse', icon: '/icons/icons8-lighthouse-64.png' },
    { type: 'Parking Space', icon: '/icons/icons8-outdoor-parking-64.png' },
    { type: 'Cave', icon: '/icons/icons8-cave-64.png' },
    { type: 'Igloo', icon: '/icons/icons8-igloo-64.png' },
    { type: 'Ryokan (Japan)', icon: '/icons/icons8-japan-64.png' },
    { type: 'Tipi', icon: '/icons/icons8-tipi-64.png' },
  ];
  